=== DAW1-25-26/Lenguaje-de-marcas/XML-JSON/ejemplos/biblioteca/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="autor" type="xs:string"/>
                            <xs:element name="año" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DAW1-25-26/Lenguaje-de-marcas/XML-JSON/ejemplos/biblioteca/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="biblioteca.xsd">
  <libro>
    <titulo>Cien años de soledad</titulo>
    <autor>Gabriel García Márquez</autor>
    <año>1967</año>
  </libro>
  <libro>
    <titulo>El amor en los tiempos del cólera</titulo>
    <autor>Gabriel García Márquez</autor>
    <año>1985</año>
  </libro>
  <libro>
    <titulo>Rayuela</titulo>
    <autor>Julio Cortázar</autor>
    <año>1963</año>
  </libro>
</biblioteca>
