=== DAW1-25-26/Lenguaje-de-marcas/XML-JSON/ejercicios/DTD/ejercicio2/aeropuerto.dtd
<!ELEMENT aeropuerto (nombre, codigo, ubicacion, terminales, servicios)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT ubicacion (ciudad, pais)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT terminales (terminal+)>
<!ELEMENT terminal (nombre, aerolineas, puertas)>
<!ATTLIST terminal 
    id NMTOKEN #REQUIRED
>
<!ELEMENT aerolineas (aerolinea+)>
<!ELEMENT aerolinea (#PCDATA)>
<!ELEMENT puertas (puerta+)>
<!ELEMENT puerta (#PCDATA)>
<!ATTLIST puerta 
    numero ID #REQUIRED
>
<!ELEMENT servicios (servicio+)>
<!ELEMENT servicio (#PCDATA)>

=== DAW1-25-26/Lenguaje-de-marcas/XML-JSON/ejercicios/DTD/ejercicio2/aeropuerto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuerto SYSTEM "aeropuerto.dtd">
<aeropuerto>
    <nombre>Aeropuerto Internacional</nombre>
    <codigo>IATA: ABC</codigo>
    <ubicacion>
        <ciudad>Ciudad ABC</ciudad>
        <pais>País XYZ</pais>
    </ubicacion>
    <terminales>
        <terminal id="1">
            <nombre>Terminal A</nombre>
            <aerolineas>
                <aerolinea>Cia. Aérea 1</aerolinea>
                <aerolinea>Cia. Aérea 2</aerolinea>
            </aerolineas>
            <puertas>
                <puerta numero="A1" />
                <puerta numero="A2" />
                <puerta numero="A3" />
            </puertas>
        </terminal>
        <terminal id="2">
            <nombre>Terminal B</nombre>
            <aerolineas>
                <aerolinea>Cia. Aérea 3</aerolinea>
                <aerolinea>Cia. Aérea 4</aerolinea>
            </aerolineas>
            <puertas>
                <puerta numero="B1" />
                <puerta numero="B2" />
                <puerta numero="B3" />
            </puertas>
        </terminal>
    </terminales>
    <servicios>
        <servicio>Restaurante</servicio>
        <servicio>Tienda Duty-Free</servicio>
        <servicio>Salas VIP</servicio>
    </servicios>
</aeropuerto>
